### ISSUE TITLE
ADD bash_completion support: autocomplete mariadb service names

### ISSUE THREAD

**Issue by allanlaal** [dokku/dokku-mariadb#102]
would be convenient if dokku mariadb:* commands would autocomplete service names to whats listed in `mariadb:list`
TABbing nothing would offer the entire list

**Comment by josegonzalez** [comment]
I'm going to close this. Plugins cannot directly support autocompletion, and any framework would need to be built into the core project before we could support it here.

**Comment by allanlaal** [comment]
WAITING FOR: https://github.com/dokku/dokku/issues/4982
