### ISSUE TITLE
Designate a data-dir at create or install

### ISSUE THREAD

**Issue by hades200082** [dokku/dokku-mariadb#143]
## Description of problem

I have a separate large drive on my host server that I want to use as the data storage location for database systems. Is it possible to specify the data-dir for this plugin either at install time or at the time I create a new service?

**Comment by josegonzalez** [comment]
Maybe the closest thing to this today is setting the `MARIADB_ROOT` and `MARIADB_HOST_ROOT` paths  as shown [here](https://github.com/dokku/dokku-mariadb/blob/master/config#L5C8-L5C20) prior to creating or interacting with a datastore. You could probably set them in `/etc/default/dokku`, as dokku sources that on start.

We don't expose the path for a given datastore as an option as it makes the internal logic surrounding datastore access a bit more complex, so the above is probably the best way to do what you want to do.

Closing the ticket for now, but let me know if you have any further questions on this topic :)
