### ISSUE TITLE
Start a new (removed) container

### ISSUE THREAD

**Issue by ignlg** [dokku/dokku-mariadb#31]
I want to call for ideas to add a new command to deploy a new container with existent configuration.

This was the case: While I was cleaning up docker containers and images, I destroyed a `dokku-mariadb` container that was stopped earlier. I've found that there's no command to deploy **again** a `dokku-mariadb` container. `mariadb:create` creates a new configuration and `mariadb:start` doesn't found the old container.

I ended up creating a new command `mariadb:deploy` that is similar to `mariadb:create` but it reads the actual configuration to deploy the container.

As I could end up pushing the feature to other plugins like `dokku-mongo`, etc, I would want to quickly discuss with you the right name and description for the command.

What do you think?

**Comment by josegonzalez** [comment]
I'm not sure what you are trying to do. Do you mean the container was destroyed so you needed another one with the same config/volume?

**Comment by ignlg** [comment]
Exactly. I need to start a new container but keep the config/volume.

`create` says that the service already exists.
`start` says that no container exists.

And both are right.

**Comment by josegonzalez** [comment]
`start` should probably warn and then create the container. That seems reasonable to me. Mind creating a pr with that functionality? I can port it to the other containers once you do.

**Comment by ignlg** [comment]
Sure, I was waiting to discuss if it should be a new command or not to create a PR.

**Comment by josegonzalez** [comment]
Closed by #44
