### ISSUE TITLE
one service with multiples databases

### ISSUE THREAD

**Issue by Kikobeats** [dokku/dokku-mariadb#35]
As you say me in https://github.com/ohardy/dokku-mariadb/pull/14#issuecomment-169491029, I could use one service container with multiple databases.

First of all, I tried to connect with the instance and create the database manually, but doesn't work:

````
MariaDB [kikoblog]> CREATE DATABASE anoter_database;
ERROR 1044 (42000): Access denied for user 'mariadb'@'%' to database 'anoter_database'
MariaDB [kikoblog]>
```

Seems like it is a permission issue. Any ideas?

One more thing: I want to use single container with multiple databases because my machine is limited and I think that is a good approach to avoid have multiple services running that is equivalent to use more machine resources. Can you confirm me that this premise is correct?

thanks for your time maintaining amazing projects! :)

**Comment by Flink** [comment]
There is a `root` user and its password should be located in `/var/lib/dokku/services/mariadb/your-service/ROOTPASSWORD`.
But you’ll have to connect to the DB directly with mariadb tools and not through the `mariadb:connect` command provided by this plugin.

**Comment by josegonzalez** [comment]
Note: this is related to the enhancement proposed [here](https://github.com/dokku/dokku-postgres/pull/44#issuecomment-161105507). If someone wants to sit down and do it, you get commit rights on all the dokku plugins and I'll buy you beers whenever you are in NYC (ask @michaelshobbs, he almost died when he went out with me :beers: ).

**Comment by Flink** [comment]
@josegonzalez I’m currently working on it https://github.com/dokku/dokku-postgres/commits/lg-multi-db-users :)

**Comment by josegonzalez** [comment]
:beers: :beers: :beers: :beers:

**Comment by Flink** [comment]
:grinning:

**Comment by josegonzalez** [comment]
Here is the proposal if anyone wants to take a stab at this:

```
# by default, simply create a `postgres` user on a database
dokku postgres:create <db>

# we store the user/pass info in a set of files
# located in
#
#     /var/lib/dokku/services/postgres/SERVICE/auth/username
#
# where the username is the name of the user, 
# and the contents are the password. Note that we
# will need to migrate all the old auth stuff over, including
# any root users.

# create a custom user
# users will have access to all databases etc. Let's not get fancy
# here. If a user wants to lock things down on their own, it's up to
# them
dokku postgres:create-user <db> <user> <pass>

# linking uses the postgres user by default
dokku postgres:link <db> <app>

# you can specify the user to use when linking
dokku postgres:link <db> <app> --user <user>

# we can also create specific databases, and we'd have a list of them here:
#
#     /var/lib/dokku/services/postgres/SERVICE/databases/name
#
dokku postgres:create-database <db> <name>

# you can specify the database *and* user to use when linking
dokku postgres:link <db> <app> --user <user> --database <name>
```

**Comment by josegonzalez** [comment]
Closing in favor of a rather large rfc here: dokku/dokku-redis/issues/64
