### ISSUE TITLE
dokku mariadb:create <service> freezes

### ISSUE THREAD

**Issue by j-a-m-l** [dokku/dokku-mariadb#46]
I've traced the execution until [functions#L257](https://github.com/dokku/dokku-mariadb/blob/master/functions#L257).

After stopping the command (Ctrl + c), the new service is frozen as "restarting" and can't be remove (it is detected as stopped), so the only way to really stop its container is `sudo docker stop <id>`.

`dokku mariadb:logs <service>` returns this (repeated more than 10 times):

```
error: database is uninitialized and password option is not specified
You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
```

**Comment by josegonzalez** [comment]
Can you try master now? I did a bit of refactoring last night, guess it wasn't well tested.

**Comment by j-a-m-l** [comment]
Yeah! It worked flawlessly. Thank you
