### ISSUE TITLE
Consider having single-instance mode

### ISSUE THREAD

**Issue by webknjaz** [dokku/dokku-mariadb#68]
Hi,

I need to have ability of running a single db process instead of spawning per-app db containers. Smth like these:
* https://github.com/krisrang/dokku-mariadb
* https://github.com/ohardy/dokku-mariadb

Is it hard to implement?

**Comment by josegonzalez** [comment]
This is planned: https://github.com/dokku/dokku-redis/issues/64

**Comment by webknjaz** [comment]
@josegonzalez thanks for the prompt reply.

Still the question was "is it hard to implement?"

I could try crafting a PR if you point me a direction.

**Comment by josegonzalez** [comment]
It's not hard, just there are lots of moving parts, as mentioned in the issue, and you'll need to be cognizant of that.
