### ISSUE TITLE
Database stuck in 'Restarting'

### ISSUE THREAD

**Issue by shrmnk** [dokku/dokku-mariadb#69]
I have a mariadb service stuck in 'Restarting'. Issue persists on reboot. Everything on apt is up-to-date. Fresh installation on DigitalOcean Ubuntu 16.04. No other software installed apart from dokku and its dependencies.

dokku plugins installed:
- letsencrypt
- mariadb
- postgres

There is just 1 other mariadb service that is running and works well.

---

`dokku mariadb:stop`

> !     Service is already stopped

`dokku mariadb:start`

> -----> Starting container
> docker: Error response from daemon: Conflict. The container name "/dokku.mariadb.bigtime-db-staging" is already in use by container "fa87f9e256425729f41155318041f30b7e37578637cd51fa178c95833ca4e858". You have to remove (or rename) that container to be able to reuse that name.
> See 'docker run --help'.

`dokku mariadb:destroy --force`

> -----> Deleting [redacted db name]
>        Deleting container data
>  !     Service is already stopped
>        Removing container
> Error response from daemon: You cannot remove a restarting container fa87f9e256425729f41155318041f30b7e37578637cd51fa178c95833ca4e858. Stop the container before attempting removal or force remove

`dokku mariadb:logs`
https://gist.github.com/shrmnk/405bc8bc2d1d47a8892c15b868923503

**Comment by josegonzalez** [comment]
Seems like the logs were deleted. If the container is in "restarting" mode, then that means it is likely in an error state. You can force remove the container and then call `dokku mariadb:start` if thats the case.

**Comment by nvirin** [comment]
Hi! I have the same problem. Even with 'dokku mariadb:create newservice'. Did you do another thing to solve it?

**Comment by josegonzalez** [comment]
@nvirin please do not comment on old issues. If you can open a new issue and provide the following information, that would be great:

```
dokku report
dokku mariadb:list
dokku mariadb:info YOUR_SERVICE
dokku mariadb:logs YOUR_SERVICE
docker ps -a
```
