### ISSUE TITLE
What is the format of schedule exactly?

### ISSUE THREAD

**Issue by kgrosvenor** [dokku/dokku-mariadb#74]
So for 3am do you mean something like 0300 ?

**Comment by josegonzalez** [comment]
From the docs:

> # CRON_SCHEDULE is a crontab expression, eg. "0 3 * * *" for each day at 3am

From wikipedia: https://en.wikipedia.org/wiki/Cron#CRON_expression

I tend to use [this site](https://crontab.guru/) when I'm having trouble figuring out what datetime someone meant, but it can be useful to figure out how to map it to the time you want.

Note that time is in server time, which hopefully you've set to UTC.
